In [45]:
import numpy as np
import pandas as pd
import ast

In [5]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [9]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [11]:
movies=movies.merge(credits,on="title")

In [13]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [17]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [19]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [21]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [31]:
movies = movies.copy()
movies.dropna(inplace=True)

In [35]:
movies.duplicated().sum()

0

In [37]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [47]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [51]:
movies['genres']=movies['genres'].apply(convert)

movies.head()

In [53]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

movies['keywords'].apply(convert)

In [58]:
movies['keywords']=movies['keywords'].apply(convert)

In [60]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [64]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [68]:
movies['cast']=movies['cast'].apply(convert3)

In [70]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [74]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [76]:
movies['crew']=movies['crew'].apply(fetch_director)

In [78]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [82]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [84]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [88]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [90]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [92]:
movies['tags']=movies['overview']+movies['genres'] + movies['keywords']+movies['cast']+movies['crew']

In [94]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [96]:
new_df=movies[['movie_id','title','tags']]

In [98]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [100]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\yugsh\AppData\Local\Temp\ipykernel_20616\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [102]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [124]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\yugsh\AppData\Local\Temp\ipykernel_20616\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [184]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [186]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [188]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [190]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\yugsh\AppData\Local\Temp\ipykernel_20616\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [191]:
import nltk

In [194]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [196]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [197]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [200]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [202]:
new_df['tags'][1300]

"new york fashion design melani carmichael suddenli find herself engag to the city' most elig bachelor. but melanie' past hold mani secrets, includ jake, the redneck husband she marri in high school, who refu to divorc her. bound and determin to end their contenti relationship onc and for all, melani sneak back home to alabama to confront her past. comedi romanc newyork marriagepropo alabama careerwoman fashiondesign reesewitherspoon joshluca patrickdempsey andytenn"

In [204]:
from sklearn.metrics.pairwise import cosine_similarity

In [206]:
similarity=cosine_similarity(vectors)

In [216]:
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.08458258116519013),
 (2, 0.08718572905786445),
 (3, 0.074458079104994),
 (4, 0.19184045508446734),
 (5, 0.1098436937909367),
 (6, 0.04047223292581764),
 (7, 0.1487044791289829),
 (8, 0.06003002251876642),
 (9, 0.09802861627917438),
 (10, 0.10397504898200727),
 (11, 0.09592022754223367),
 (12, 0.09004503377814962),
 (13, 0.04559607525875532),
 (14, 0.12996881122750908),
 (15, 0.06367145399670132),
 (16, 0.08000711205939975),
 (17, 0.14165281524036175),
 (18, 0.09620723036050562),
 (19, 0.08489527199560176),
 (20, 0.05881716976750462),
 (21, 0.11115400287534567),
 (22, 0.0685591170191061),
 (23, 0.08718572905786445),
 (24, 0.05405405405405406),
 (25, 0.03465834966066909),
 (26, 0.1559625734730109),
 (27, 0.1894422005883515),
 (28, 0.11624763874381927),
 (29, 0.06590621627456203),
 (30, 0.06774581282657174),
 (31, 0.16120647005479025),
 (32, 0.0863465783552691),
 (33, 0.09863939238321438),
 (34, 0.0),
 (35, 0.10067340828210367),
 (36, 0.17348855898381338),
 (37, 0.08000711205939975),
 (38, 0.08219949365267865),
 (39, 0.08336550215650926),
 (40, 0.07798128673650545),
 (41, 0.1678603981989089),
 (42, 0.0),
 (43, 0.09208185110322616),
 (44, 0.03427955850955305),
 (45, 0.08284930213349333),
 (46, 0.14097096860865022),
 (47, 0.199363055707225),
 (48, 0.08561170049453902),
 (49, 0.059053859535749265),
 (50, 0.1144727614064285),
 (51, 0.0803381317273391),
 (52, 0.1487044791289829),
 (53, 0.04355035563093422),
 (54, 0.03163859985841663),
 (55, 0.0713262951621492),
 (56, 0.14019992744655632),
 (57, 0.024507154069793594),
 (58, 0.06839411288813299),
 (59, 0.07398532461669939),
 (60, 0.0186145197762485),
 (61, 0.23490461932490855),
 (62, 0.08489527199560176),
 (63, 0.08284930213349333),
 (64, 0.03001501125938321),
 (65, 0.01979131233319198),
 (66, 0.02279803762937766),
 (67, 0.16673100431301852),
 (68, 0.1221125021745327),
 (69, 0.026936179620310644),
 (70, 0.07702442489446452),
 (71, 0.07435223956449145),
 (72, 0.13699915608779772),
 (73, 0.03355780276070122),
 (74, 0.20518233866439894),
 (75, 0.10529962529853128),
 (76, 0.07271792483455794),
 (77, 0.014588051152682587),
 (78, 0.05134961659630968),
 (79, 0.06263607679944924),
 (80, 0.05114214254947678),
 (81, 0.11168711865749101),
 (82, 0.07702442489446452),
 (83, 0.18065550087085797),
 (84, 0.12527215359889848),
 (85, 0.11565903932254226),
 (86, 0.07194017065667525),
 (87, 0.11277677488692017),
 (88, 0.09158437663089954),
 (89, 0.058352204610730346),
 (90, 0.06213697660012),
 (91, 0.16916516233038026),
 (92, 0.06367145399670132),
 (93, 0.07194017065667525),
 (94, 0.1898315991504998),
 (95, 0.14237369936287486),
 (96, 0.07798128673650545),
 (97, 0.07045670884515312),
 (98, 0.07702442489446452),
 (99, 0.02702702702702703),
 (100, 0.07009996372327816),
 (101, 0.07798128673650545),
 (102, 0.12629480039223434),
 (103, 0.0803381317273391),
 (104, 0.056388387443460086),
 (105, 0.10514994558491725),
 (106, 0.06314740019611717),
 (107, 0.06263607679944924),
 (108, 0.14704292441876157),
 (109, 0.06575959492214292),
 (110, 0.04559607525875532),
 (111, 0.1522038868295523),
 (112, 0.07798128673650545),
 (113, 0.04393747751637468),
 (114, 0.04649905549752771),
 (115, 0.04433510985214727),
 (116, 0.048478616556371965),
 (117, 0.06003002251876642),
 (118, 0.03427955850955305),
 (119, 0.04393747751637468),
 (120, 0.0),
 (121, 0.11624763874381927),
 (122, 0.11810771907149853),
 (123, 0.11290968804428622),
 (124, 0.06839411288813299),
 (125, 0.07726033486461518),
 (126, 0.13513513513513514),
 (127, 0.14797064923339878),
 (128, 0.0),
 (129, 0.09394227846020416),
 (130, 0.027399831217559546),
 (131, 0.106676149412533),
 (132, 0.04559607525875532),
 (133, 0.028618190351607124),
 (134, 0.13151918984428584),
 (135, 0.0),
 (136, 0.023728949893812478),
 (137, 0.030528125543633176),
 (138, 0.12996881122750908),
 (139, 0.12141669877745292),
 (140, 0.04559607525875532),
 (141, 0.0885807893036239),
 (142, 0.08718572905786445),
 (143, 0.08787495503274936),
 (144, 0.050734628943184104),
 (145, 0.019510570275964215),
 (146, 0.01643989873053573),
 (147, 0.056388387443460086),
 (148, 0.09863939238321438),
 (149, 0.15719549837837185),
 (150, 0.16646698038757363),
 (151, 0.2056773510573183),
 (152, 0.08458258116519013),
 (153, 0.07974522228289),
 (154, 0.06213697660012),
 (155, 0.020712325533373332),
 (156, 0.059808916712167495),
 (157, 0.10067340828210367),
 (158, 0.1354916256531435),
 (159, 0.0644825880219161),
 (160, 0.11869522585912262),
 (161, 0.03224129401095805),
 (162, 0.03355780276070122),
 (163, 0.05134961659630968),
 (164, 0.08108108108108109),
 (165, 0.04649905549752771),
 (166, 0.12683657235796025),
 (167, 0.09158437663089954),
 (168, 0.17757120130114434),
 (169, 0.08948747402853657),
 (170, 0.10793322294408637),
 (171, 0.02302046277580654),
 (172, 0.21524880100025257),
 (173, 0.02348556961505104),
 (174, 0.07897471897389846),
 (175, 0.07194017065667525),
 (176, 0.029526929767874632),
 (177, 0.0),
 (178, 0.024784079854830485),
 (179, 0.07352146220938077),
 (180, 0.022371868507134143),
 (181, 0.04559607525875532),
 (182, 0.1186447494690624),
 (183, 0.0713262951621492),
 (184, 0.17757120130114434),
 (185, 0.05134961659630968),
 (186, 0.059808916712167495),
 (187, 0.1559625734730109),
 (188, 0.022371868507134143),
 (189, 0.1162476387438193),
 (190, 0.08561170049453902),
 (191, 0.04956815970966097),
 (192, 0.047457899787624956),
 (193, 0.07983920607777244),
 (194, 0.0),
 (195, 0.06003002251876642),
 (196, 0.05264981264926564),
 (197, 0.037470006725398436),
 (198, 0.058123819371909635),
 (199, 0.08867021970429453),
 (200, 0.11028219331407116),
 (201, 0.0),
 (202, 0.03163859985841663),
 (203, 0.08458258116519013),
 (204, 0.050141221056390024),
 (205, 0.07543142864047142),
 (206, 0.11241002017619531),
 (207, 0.07798128673650545),
 (208, 0.12427395320024),
 (209, 0.0685591170191061),
 (210, 0.07610194341477616),
 (211, 0.024784079854830485),
 (212, 0.0665026647782209),
 (213, 0.059808916712167495),
 (214, 0.0),
 (215, 0.06711560552140243),
 (216, 0.06575959492214292),
 (217, 0.0863465783552691),
 (218, 0.03874921291460643),
 (219, 0.09320546490018),
 (220, 0.18009006755629928),
 (221, 0.047960113771116836),
 (222, 0.08094446585163528),
 (223, 0.10529962529853128),
 (224, 0.06117355427146393),
 (225, 0.047457899787624956),
 (226, 0.030528125543633176),
 (227, 0.08336550215650926),
 (228, 0.11185934253567072),
 (229, 0.10892898631973956),
 (230, 0.0930725988812425),
 (231, 0.0),
 (232, 0.11277677488692017),
 (233, 0.10514994558491725),
 (234, 0.08710071126186844),
 (235, 0.07702442489446452),
 (236, 0.11277677488692017),
 (237, 0.06711560552140244),
 (238, 0.11241002017619531),
 (239, 0.09248165577087424),
 (240, 0.047960113771116836),
 (241, 0.08000711205939975),
 (242, 0.08219949365267865),
 (243, 0.09394227846020416),
 (244, 0.09320546490018),
 (245, 0.08219949365267865),
 (246, 0.07696578428840449),
 (247, 0.0),
 (248, 0.04559607525875532),
 (249, 0.14019992744655632),
 (250, 0.0),
 (251, 0.04244763599780088),
 (252, 0.02054987341316966),
 (253, 0.06367145399670132),
 (254, 0.07045670884515312),
 (255, 0.0),
 (256, 0.11314714296070713),
 (257, 0.05405405405405406),
 (258, 0.01793740008335438),
 (259, 0.06213697660012),
 (260, 0.20668850837512243),
 (261, 0.024507154069793594),
 (262, 0.10793322294408637),
 (263, 0.09863939238321438),
 (264, 0.0),
 (265, 0.027788500718836418),
 (266, 0.10028244211278005),
 (267, 0.06711560552140244),
 (268, 0.0533380747062665),
 (269, 0.03001501125938321),
 (270, 0.08948747402853657),
 (271, 0.07271792483455794),
 (272, 0.028194193721730043),
 (273, 0.021402925123634755),
 (274, 0.09097816785925636),
 (275, 0.1453095484297741),
 (276, 0.06327719971683327),
 (277, 0.05381220025006314),
 (278, 0.1186447494690624),
 (279, 0.07118684968143743),
 (280, 0.0),
 (281, 0.06590621627456203),
 (282, 0.02279803762937766),
 (283, 0.027788500718836418),
 (284, 0.0186145197762485),
 (285, 0.01979131233319198),
 (286, 0.07859774918918593),
 (287, 0.02632490632463282),
 (288, 0.027788500718836418),
 (289, 0.04649905549752771),
 (290, 0.06327719971683327),
 (291, 0.050141221056390024),
 (292, 0.09004503377814962),
 (293, 0.03001501125938321),
 (294, 0.1453095484297741),
 (295, 0.106676149412533),
 (296, 0.03929887459459296),
 (297, 0.04474373701426829),
 (298, 0.0),
 (299, 0.06025359879550432),
 (300, 0.17348855898381338),
 (301, 0.09491579957524988),
 (302, 0.07045670884515312),
 (303, 0.028194193721730043),
 (304, 0.06667259338283313),
 (305, 0.1926263261127128),
 (306, 0.08219949365267865),
 (307, 0.11022596991336672),
 (308, 0.0685591170191061),
 (309, 0.06327719971683327),
 (310, 0.03106848830006),
 (311, 0.1522038868295523),
 (312, 0.10146925788636821),
 (313, 0.055577001437672836),
 (314, 0.0),
 (315, 0.08458258116519013),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.10067340828210367),
 (320, 0.03106848830006),
 (321, 0.0),
 (322, 0.213352298825066),
 (323, 0.03001501125938321),
 (324, 0.024507154069793594),
 (325, 0.09672388203287416),
 (326, 0.05723638070321425),
 (327, 0.027399831217559546),
 (328, 0.027399831217559546),
 (329, 0.08000711205939975),
 (330, 0.10146925788636821),
 (331, 0.09119215051751065),
 (332, 0.10810810810810811),
 (333, 0.024784079854830485),
 (334, 0.09802861627917438),
 (335, 0.04697113923010208),
 (336, 0.07009996372327816),
 (337, 0.04604092555161308),
 (338, 0.0),
 (339, 0.04956815970966097),
 (340, 0.050141221056390024),
 (341, 0.08336550215650926),
 (342, 0.1633934794796094),
 (343, 0.019510570275964215),
 (344, 0.03001501125938321),
 (345, 0.023249527748763855),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06213697660012),
 (349, 0.07610194341477616),
 (350, 0.04956815970966097),
 (351, 0.0),
 (352, 0.027788500718836418),
 (353, 0.041757384532966166),
 (354, 0.02196873875818734),
 (355, 0.036992662308349696),
 (356, 0.09158437663089952),
 (357, 0.0),
 (358, 0.06105625108726635),
 (359, 0.03163859985841663),
 (360, 0.02122381799890044),
 (361, 0.07610194341477616),
 (362, 0.09672388203287416),
 (363, 0.10042266465917388),
 (364, 0.023728949893812478),
 (365, 0.07610194341477616),
 (366, 0.05723638070321425),
 (367, 0.0),
 (368, 0.13151918984428584),
 (369, 0.1283740414907742),
 (370, 0.05134961659630968),
 (371, 0.09695723311274393),
 (372, 0.047960113771116836),
 (373, 0.1752499093081954),
 (374, 0.038482892144202245),
 (375, 0.06213697660011999),
 (376, 0.047457899787624956),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05141933776432957),
 (380, 0.05264981264926564),
 (381, 0.08489527199560176),
 (382, 0.0),
 (383, 0.04433510985214727),
 (384, 0.029061909685954818),
 (385, 0.0),
 (386, 0.022167554926073633),
 (387, 0.023980056885558418),
 (388, 0.0),
 (389, 0.0885807893036239),
 (390, 0.02666903735313325),
 (391, 0.05733298225836872),
 (392, 0.030528125543633176),
 (393, 0.0),
 (394, 0.025070610528195012),
 (395, 0.05264981264926564),
 (396, 0.04433510985214727),
 (397, 0.05264981264926564),
 (398, 0.0),
 (399, 0.023980056885558418),
 (400, 0.09158437663089952),
 (401, 0.03106848830006),
 (402, 0.07897471897389846),
 (403, 0.08419653359482289),
 (404, 0.058123819371909635),
 (405, 0.056388387443460086),
 (406, 0.021049133398705722),
 (407, 0.021586644588817275),
 (408, 0.03287979746107146),
 (409, 0.0),
 (410, 0.09913631941932194),
 (411, 0.0533380747062665),
 (412, 0.09695723311274393),
 (413, 0.1389425035941821),
 (414, 0.03001501125938321),
 (415, 0.05381220025006314),
 (416, 0.05134961659630968),
 (417, 0.03287979746107146),
 (418, 0.03587480016670876),
 (419, 0.06974858324629157),
 (420, 0.1139901881468883),
 (421, 0.02348556961505104),
 (422, 0.11810771907149853),
 (423, 0.041757384532966166),
 (424, 0.037470006725398436),
 (425, 0.06475993376645182),
 (426, 0.05446449315986979),
 (427, 0.02702702702702703),
 (428, 0.056573571480353566),
 (429, 0.0),
 (430, 0.05134961659630968),
 (431, 0.024507154069793594),
 (432, 0.11624763874381928),
 (433, 0.03163859985841663),
 (434, 0.0),
 (435, 0.03587480016670876),
 (436, 0.0),
 (437, 0.02632490632463282),
 (438, 0.12392039927415242),
 (439, 0.02666903735313325),
 (440, 0.025070610528195012),
 (441, 0.058123819371909635),
 (442, 0.04604092555161308),
 (443, 0.06475993376645182),
 (444, 0.0),
 (445, 0.10028244211278005),
 (446, 0.02348556961505104),
 (447, 0.06532553344640132),
 (448, 0.021586644588817275),
 (449, 0.11115400287534567),
 (450, 0.021586644588817275),
 (451, 0.025367314471592052),
 (452, 0.03106848830006),
 (453, 0.024784079854830485),
 (454, 0.11742784807525519),
 (455, 0.061649620239508984),
 (456, 0.04393747751637468),
 (457, 0.08718572905786445),
 (458, 0.04393747751637468),
 (459, 0.03504998186163908),
 (460, 0.024507154069793594),
 (461, 0.14309095175803563),
 (462, 0.03271662128033808),
 (463, 0.03287979746107146),
 (464, 0.0),
 (465, 0.0),
 (466, 0.14704292441876154),
 (467, 0.10701462561817378),
 (468, 0.028194193721730043),
 (469, 0.06025359879550432),
 (470, 0.04604092555161308),
 (471, 0.06475993376645182),
 (472, 0.10959932487023819),
 (473, 0.09394227846020416),
 (474, 0.0),
 (475, 0.04433510985214727),
 (476, 0.1371182340382122),
 (477, 0.0),
 (478, 0.05479966243511909),
 (479, 0.0891578689526865),
 (480, 0.09913631941932194),
 (481, 0.0),
 (482, 0.022167554926073633),
 (483, 0.12655439943366653),
 (484, 0.029526929767874632),
 (485, 0.0533380747062665),
 (486, 0.08099356774626426),
 (487, 0.1289651760438322),
 (488, 0.06746792083200746),
 (489, 0.0),
 (490, 0.14349920066683505),
 (491, 0.1011805823145441),
 (492, 0.07702442489446452),
 (493, 0.03106848830006),
 (494, 0.0),
 (495, 0.19344776406574832),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0685591170191061),
 (499, 0.0),
 (500, 0.02632490632463282),
 (501, 0.08284930213349333),
 (502, 0.1354916256531435),
 (503, 0.07610194341477615),
 (504, 0.0),
 (505, 0.1371182340382122),
 (506, 0.03504998186163908),
 (507, 0.25903973506580724),
 (508, 0.10269923319261937),
 (509, 0.022371868507134143),
 (510, 0.10028244211278005),
 (511, 0.09320546490018),
 (512, 0.027788500718836418),
 (513, 0.1487044791289829),
 (514, 0.04956815970966097),
 (515, 0.025070610528195012),
 (516, 0.028618190351607124),
 (517, 0.0),
 (518, 0.04474373701426829),
 (519, 0.0),
 (520, 0.0),
 (521, 0.025367314471592052),
 (522, 0.024507154069793594),
 (523, 0.04901430813958719),
 (524, 0.0),
 (525, 0.047960113771116836),
 (526, 0.028618190351607124),
 (527, 0.03355780276070122),
 (528, 0.022581937608857246),
 (529, 0.1696751579473019),
 (530, 0.056388387443460086),
 (531, 0.04697113923010208),
 (532, 0.021586644588817275),
 (533, 0.06105625108726635),
 (534, 0.08489527199560176),
 (535, 0.09913631941932194),
 (536, 0.11399018814688831),
 (537, 0.0685591170191061),
 (538, 0.0),
 (539, 0.2537477434955704),
 (540, 0.07610194341477616),
 (541, 0.10701462561817376),
 (542, 0.037470006725398436),
 (543, 0.07194017065667525),
 (544, 0.056388387443460086),
 (545, 0.025070610528195012),
 (546, 0.0644825880219161),
 (547, 0.08336550215650926),
 (548, 0.0),
 (549, 0.1211965413909299),
 (550, 0.025070610528195012),
 (551, 0.03822198817224581),
 (552, 0.0),
 (553, 0.029061909685954818),
 (554, 0.0),
 (555, 0.04559607525875532),
 (556, 0.02702702702702703),
 (557, 0.12392039927415242),
 (558, 0.0),
 (559, 0.030528125543633176),
 (560, 0.03653310829007939),
 (561, 0.03224129401095805),
 (562, 0.03106848830006),
 (563, 0.025993762245501817),
 (564, 0.09004503377814962),
 (565, 0.04433510985214727),
 (566, 0.024239308278185982),
 (567, 0.025367314471592052),
 (568, 0.1430909517580356),
 (569, 0.047960113771116836),
 (570, 0.0685591170191061),
 (571, 0.04280585024726951),
 (572, 0.10887588907733554),
 (573, 0.021049133398705722),
 (574, 0.023728949893812478),
 (575, 0.04604092555161308),
 (576, 0.05264981264926564),
 (577, 0.20032733246124987),
 (578, 0.03796631983009995),
 (579, 0.14097096860865022),
 (580, 0.024507154069793594),
 (581, 0.14763464883937316),
 (582, 0.2484013136974297),
 (583, 0.03822198817224581),
 (584, 0.08219949365267865),
 (585, 0.024784079854830485),
 (586, 0.04559607525875532),
 (587, 0.07194017065667525),
 (588, 0.025993762245501817),
 (589, 0.1178966237837789),
 (590, 0.030528125543633176),
 (591, 0.06367145399670132),
 (592, 0.021402925123634755),
 (593, 0.0),
 (594, 0.050141221056390024),
 (595, 0.162746694241347),
 (596, 0.09394227846020416),
 (597, 0.06003002251876642),
 (598, 0.036760731104690386),
 (599, 0.027788500718836418),
 (600, 0.06906138832741962),
 (601, 0.033912921674035035),
 (602, 0.09208185110322616),
 (603, 0.05479966243511909),
 (604, 0.06711560552140244),
 (605, 0.02666903735313325),
 (606, 0.0),
 (607, 0.058531710827892644),
 (608, 0.0),
 (609, 0.047457899787624956),
 (610, 0.05881716976750462),
 (611, 0.023249527748763855),
 (612, 0.06420877537090426),
 (613, 0.036760731104690386),
 (614, 0.04956815970966097),
 (615, 0.06213697660012),
 (616, 0.03504998186163908),
 (617, 0.050734628943184104),
 (618, 0.08948747402853657),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06575959492214292),
 (622, 0.021402925123634755),
 (623, 0.0),
 (624, 0.10283867552865913),
 (625, 0.03163859985841663),
 (626, 0.08336550215650926),
 (627, 0.11028219331407116),
 (628, 0.0),
 (629, 0.04901430813958719),
 (630, 0.024784079854830485),
 (631, 0.05134961659630968),
 (632, 0.07798128673650545),
 (633, 0.022581937608857246),
 (634, 0.07521183158458504),
 (635, 0.0665026647782209),
 (636, 0.023728949893812478),
 (637, 0.024507154069793594),
 (638, 0.03355780276070122),
 (639, 0.0),
 (640, 0.06070834938872646),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10146925788636821),
 (644, 0.050734628943184104),
 (645, 0.04474373701426829),
 (646, 0.0533380747062665),
 (647, 0.04901430813958719),
 (648, 0.030528125543633176),
 (649, 0.0),
 (650, 0.05264981264926564),
 (651, 0.0),
 (652, 0.04355035563093422),
 (653, 0.10762440050012628),
 (654, 0.10524566699352861),
 (655, 0.024239308278185982),
 (656, 0.0),
 (657, 0.03504998186163908),
 (658, 0.04901430813958719),
 (659, 0.02567480829815484),
 (660, 0.0949157995752499),
 (661, 0.16839306718964578),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06105625108726635),
 (665, 0.06906138832741962),
 (666, 0.050734628943184104),
 (667, 0.0),
 (668, 0.1371182340382122),
 (669, 0.03587480016670876),
 (670, 0.017727598712973542),
 (671, 0.06906138832741962),
 (672, 0.028618190351607124),
 (673, 0.02023611646290882),
 (674, 0.07194017065667525),
 (675, 0.04559607525875532),
 (676, 0.029061909685954818),
 (677, 0.025367314471592052),
 (678, 0.11624763874381927),
 (679, 0.0),
 (680, 0.07610194341477616),
 (681, 0.027788500718836418),
 (682, 0.02023611646290882),
 (683, 0.04901430813958719),
 (684, 0.0),
 (685, 0.03355780276070122),
 (686, 0.03224129401095805),
 (687, 0.10529962529853128),
 (688, 0.04393747751637468),
 (689, 0.0),
 (690, 0.025367314471592052),
 (691, 0.06003002251876642),
 (692, 0.11083777463036817),
 (693, 0.03427955850955305),
 (694, 0.022167554926073633),
 (695, 0.06711560552140244),
 (696, 0.021586644588817275),
 (697, 0.0),
 (698, 0.04393747751637468),
 (699, 0.03874921291460643),
 (700, 0.029061909685954818),
 (701, 0.058123819371909635),
 (702, 0.02279803762937766),
 (703, 0.021586644588817275),
 (704, 0.06906138832741962),
 (705, 0.024784079854830485),
 (706, 0.02196873875818734),
 (707, 0.0),
 (708, 0.025070610528195012),
 (709, 0.020878692266483083),
 (710, 0.058531710827892644),
 (711, 0.05264981264926564),
 (712, 0.0),
 (713, 0.025070610528195012),
 (714, 0.0),
 (715, 0.10067340828210367),
 (716, 0.027399831217559546),
 (717, 0.0),
 (718, 0.04559607525875532),
 (719, 0.0),
 (720, 0.02666903735313325),
 (721, 0.03287979746107146),
 (722, 0.0),
 (723, 0.025070610528195012),
 (724, 0.023980056885558418),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03120812265889869),
 (728, 0.07352146220938079),
 (729, 0.04956815970966097),
 (730, 0.030660569226416797),
 (731, 0.05264981264926564),
 (732, 0.06839411288813299),
 (733, 0.06213697660011999),
 (734, 0.06774581282657174),
 (735, 0.06774581282657174),
 (736, 0.029061909685954818),
 (737, 0.07798128673650545),
 (738, 0.0),
 (739, 0.03874921291460643),
 (740, 0.10984369379093671),

In [224]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, 0.29061909685954823),
 (3728, 0.26401000024165),
 (507, 0.25903973506580724),
 (539, 0.2537477434955704),
 (2405, 0.2507061052819501)]

In [208]:
similarity[1]

array([0.08458258, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

In [210]:
new_df[new_df['title']=='Batman Begins'].index[0]

119

In [280]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [286]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [262]:
new_df.iloc[1214].title

'Aliens vs Predator: Requiem'

In [288]:
import pickle

In [292]:
with open('movies.pkl', 'wb') as f:
    pickle.dump(new_df, f)

In [294]:
with open('similarity.pkl', 'wb') as f:
    pickle.dump(similarity, f)